### ISSUE TITLE
Updating testcases to Feature all Functions!

### ISSUE THREAD

**Issue by felixfong227** [AminoJS/Amino.JS#28]
Add new test cases and examples for the new users fetching function

**Comment by moelrobi** [comment]
Already getting served in a Branch i created.

**Comment by felixfong227** [comment]
Plz do help me link the branch and also update the GitHub's project thanks

**Comment by akatsukilevi** [comment]
Hey, sorry for ask this here, but my discord glitched and it kicked me from all the servers, can you send the invite to the server?
