### ISSUE TITLE
Author undefined in getChat function

### ISSUE THREAD

**Issue by moelrobi** [AminoJS/Amino.JS#42]
**Describe the bug**
In amino.getChat() there is a bug that the authors name is not defined

**Expected behavior**
author.name is undefinded, due to backend change.

**Comment by felixfong227** [comment]
Question @moelrobi I can't even see there is an `author.name` key inside the return object
![image](https://user-images.githubusercontent.com/13918481/44584948-32ff4000-a7dd-11e8-8a68-1d63e5a6b2ae.png)

**Comment by moelrobi** [comment]
helpers/sorter.js:

```
sendMessageSorter: (uid, element) => {

return {

'threadId': uid,

'messageId': element.messageId,

'msg': element.content,

'type': element.type,

'author': {

'uid': element.author.uid,

'name': element.author.name,

'level': element.author.level,

'role': element.author.role

}

};

},

```

The Backend now needs 
> element.author.nickname 



_Sent from my Galaxy S7 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by felixfong227** [comment]
Fixed the issue at https://github.com/AminoJS/Amino.JS/tree/issue42 😄

**Comment by akatsukilevi** [comment]
I tested the issue fix, works perfectly

**Comment by felixfong227** [comment]
@akatsukilevi You mean the branch I pushed or you are referring another branch 😹

**Comment by akatsukilevi** [comment]
The one you pushed https://github.com/AminoJS/Amino.JS/tree/issue42 (sorry for late reply)

**Comment by felixfong227** [comment]
Thanks @akatsukilevi , I’m going to close this issue now, if this problem occurred again(which I think it will🤣) we shall reopen this issue or just simply open an other issue ticket

**Comment by moelrobi** [comment]
It should not.

Felix Fong <notifications@github.com> schrieb am Do., 18. Okt. 2018, 19:11:

**Comment by akatsukilevi** [comment]
You're welcome!

> Thanks @akatsukilevi , I’m going to close this issue now, if this problem occurred again(which I think it will) we shall reopen this issue or just simply open an other issue ticket
