### ISSUE TITLE
Look for open Flags

### ISSUE THREAD

**Issue by moelrobi** [AminoJS/Amino.JS#49]
http://service.narvii.com/api/v1/x159192087/s/flag?status=pending&type=all&start=0&size=1

//FOR Flagged Stuff
//only Leaders can use this

**Comment by akatsukilevi** [comment]
I'll be making a new Update Based on the 3.0.0-nightly, fix the things who are set for the Pull Request and add theses new ones
@moelrobi can you assign the task to me?

**Comment by moelrobi** [comment]
@akatsukilevi 
Welcome back from the dead first of all.

Assigned to you! But please keep in mind that I want to get 3.0.0 out asap since it's been long in development. :thinking:

**Comment by akatsukilevi** [comment]
Thanks, sorry for ages dead
Work really took over me, barely could have time to sleep myself XD

And okay, i'll be making the updates to the 3.0.0

**Comment by akatsukilevi** [comment]
Did the module ``openFlags.js``, and wrote the example already. This new feature will be added at the 3.0.0-nightly
Closing due to finished
