### ISSUE TITLE
Remove request-promise and request as dependencies

### ISSUE THREAD

**Issue by moelrobi** [AminoJS/Amino.JS#52]
I would like to remove the dependencies "request" and "request-promise", hence they are only used one Time in `upload.js`. Since Request is not really used and Narviis API is accepting Base64, we can maybe migrate that to isomorphic-fetch. Since @akatsukilevi you are currently our API dumper i want your Opinon on this. :)

**Comment by akatsukilevi** [comment]
The ``request`` and ``request-promise`` can be removed. I'm using it on the ``upload.js``because i was lazy to search for the ``isomorphic-fetch``documentation and i went to the one i already knew XD
I'll be making the changes to be able to remove the dependencies

**Comment by akatsukilevi** [comment]
The dependency on ``request`` and ``request-promise`` is not needed anymore. I removed it from the ``packages.json``, and the ``upload.js`` now uses the ``isomorphic-fetch``

EDIT: i didn't commited the change yet, because i want to fix the ``JSON parse error`` bug together on it
