### ISSUE TITLE
JSON.parse Errors when Amino is having Service Maintence 

### ISSUE THREAD

**Issue by moelrobi** [AminoJS/Amino.JS#53]
**Describe the bug**
If Amino is down (Statuscode 500, etc.) then JSON.parse tries to compile the HTML Nginx File to JSON which is not going to work. 

**To Reproduce**
Wait until Amino Breaks and then try to interact with the API. (easy tbh since amino is down every 3 Hours or so)

**Expected behavior**
A Error Handler trying to tell the person with a different Status code that Amino is Down.

**Comment by akatsukilevi** [comment]
NOTE: i managed to emulate part of the Amino Servers on a Linux workstation i have. I'll emulate a 500 error code and make a error handling to check if the amino is down before actually make a request

**Comment by moelrobi** [comment]
Just put this still into the 3.0.0 Update.

**Comment by akatsukilevi** [comment]
Okay, got it

**Comment by akatsukilevi** [comment]
Fixed. Now all of them throw an error like: ``Amino appears to be offline. Response status = [[ERROR CODE]]``.
Closing this issue as fixed
