### ISSUE TITLE
Kick someone from a Chatroom

### ISSUE THREAD

**Issue by moelrobi** [AminoJS/Amino.JS#55]
**Describe the solution you'd like**
Endpoint:
DELETE /api/v1/<CommunityID>/s/chat/thread/<ChatID>/member/<UserID>?allowRejoin=<0|1> HTTP/1.1

**Comment by akatsukilevi** [comment]
Got it. Will be adding it at the update

**Comment by akatsukilevi** [comment]
Did the module ``removeChat.js``, and wrote the example already. This new feature will be added at the 3.0.0-nightly
Closing due to finished
