### ISSUE TITLE
Invite someone in the Chat

### ISSUE THREAD

**Issue by moelrobi** [AminoJS/Amino.JS#56]
**Describe the solution you'd like**
Endpoint:
POST /api/v1/<ComID>/s/chat/thread/<ChatID>/member/invite HTTP/1.1
JSON:
```json
{
"uids": ["Array of UserID's to be invited to Chat", "MUST BE ABLE TO (i.e. the invitee needs to follow the inviter)"],
"timestamp": "A JS Timestamp"
}
```

**Comment by akatsukilevi** [comment]
Got it. Will be adding at the update

**Comment by akatsukilevi** [comment]
Did the module ``inviteChat.js``, and wrote the example already. This new feature will be added at the 3.0.0-nightly
Closing due to finished
