### ISSUE TITLE
Fire a event when message is received?

### ISSUE THREAD

**Issue by kurai021** [AminoJS/Amino.JS#59]
I want to do a bot for Amino but I can't find a method to get the last message, fire an event and send a message (not using intervals), maybe like Telegram bots API

**Comment by akatsukilevi** [comment]
Last message from a specific chat you mean?

**Comment by kurai021** [comment]
I want to get the last message received from a chat in real time. But I'm not sure that using an interval every certain number of seconds calling getChat is the smartest way to do it

**Comment by akatsukilevi** [comment]
First of all, i'm really sorry for the delay!
I was checking the Amino on a MIMT proxy over my computer, and i checked that it does exactly this way. You can make a function to compare the message list. If the list it just got is the same as the list it already have, it can fire a new message event, sending only the messages who are different

**Comment by kurai021** [comment]
thanks for your answer :D
