### ISSUE TITLE
Login Error: SID is not defined.[object Object]

### ISSUE THREAD

**Issue by Rodolfoam3** [AminoJS/Amino.JS#64]
I must missunderstood how to login my account, but it's still giving the same error.
Can you help me with this?

![chrome_MZ4a3Q96OY](https://user-images.githubusercontent.com/30196326/64268403-eaba4800-cf2f-11e9-998b-257824844619.png)

**Comment by Rodolfoam3** [comment]
Huh, I'm dumb. I didn't verify my email. Sorry.
Closing the issue...

**Comment by akatsukilevi** [comment]
It throws this error when it can't execute login due to some problem(account doesn't exists, wrong username/password, account not verified, etc)
